# Generated by Django 4.1.1 on 2022-09-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_genrefilmwork_options_filmwork_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmwork',
            name='certificate',
        ),
    ]
